Added ansible

diff --git a/wercker-box.yml b/wercker-box.yml
--- a/wercker-box.yml
+++ b/wercker-box.yml
@@ -8,10 +8,11 @@ packages:
   - oracle-java7
   - mysql-client
   - fabric
+  - ansible
 script: |-
   # Remove java from base box
   sudo apt-get purge openjdk-\* icedtea-\* icedtea6-\*
-  
+
   # Assert that java is not available anymore
   ! type java || { echo "I expected java to be not available. Java version is: $(java -version). Aborting."; exit 1; }
 
@@ -22,10 +23,10 @@ script: |-
   # Accept the oracle license
   echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
   echo debconf shared/accepted-oracle-license-v1-1 seen true |  sudo debconf-set-selections
-  
+
   # Install oracle-java7
   sudo apt-get install oracle-java7-installer -y -qq
-  
+
   # We should have java again
   type java || { echo "I expected java to be available after oracle-java7-installer installation. Aborting."; exit 1; }
 
@@ -33,7 +34,7 @@ script: |-
   wget -O $WERCKER_CACHE_DIR/maven.tgz http://www.us.apache.org/dist/maven/maven-3/3.2.1/binaries/apache-maven-3.2.1-bin.tar.gz
   cd /opt && sudo tar xzvf $WERCKER_CACHE_DIR/maven.tgz && sudo ln -s apache-maven-* maven
   sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn
-  
+
   type mvn || { echo "I expected maven to be available. Aborting."; exit 1; }
 
   # Install mysql-client
@@ -46,3 +47,9 @@ script: |-
 
   type fab || { echo "I expected fab to be available. Aborting."; exit 1; }
 
+  # Install ansible
+  sudo apt-add-repository ppa:ansible/ansible
+  sudo apt-get update
+  sudo apt-get install ansible
+
+  type ansible || { echo "I expected ansible to be available. Aborting."; exit 1; }
